addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.2")
addSbtPlugin("org.typelevel" % "sbt-typelevel-ci-release" % "0.8.4")
addSbtPlugin("org.typelevel" % "sbt-typelevel-mergify" % "0.8.4")
addSbtPlugin("org.typelevel" % "sbt-typelevel-settings" % "0.8.4")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.20.2")
addSbtPlugin("com.disneystreaming.smithy4s"  % "smithy4s-sbt-codegen" % "0.18.46")
